(function () {
  "use strict";
  // Each lesson pairs an experiment with a prediction and explanatory feedback.
  const fe = [
    [
      "stress",
      "The stress laboratory",
      "Make the invisible visible.",
      "Apply a load, deform a mesh, and inspect the forces carried by each element.",
      "A structure turns an external load into internal stress. This experiment solves a two-dimensional, linear-elastic plane-stress model, then lifts its computed field into a three-dimensional view. The thickness is visualized; there are no through-thickness solution degrees of freedom.",
      "σᵥ = √(σₓ² − σₓσᵧ + σᵧ² + 3τₓᵧ²)",
      "Change the load before changing the mesh. In linear elasticity, doubling the force doubles displacement and stress.",
      "If you double the load while keeping everything else fixed, what happens to displacement?",
      ["It doubles.", "It stays the same.", "It increases fourfold."],
      0,
      "The system K u = f is linear. With K unchanged, twice the force gives twice the displacement.",
    ],
    [
      "foundations",
      "Physics & boundaries",
      "Every solution starts with constraints.",
      "Compare bending with axial tension and follow the load to its supports.",
      "A boundary condition defines what the model can do. The left edge here has both displacement components fixed. The right edge carries a distributed traction with a specified total force. Support reactions must balance that force. An unconstrained structure has rigid-body modes and cannot be solved as a unique static displacement problem.",
      "Σ F + Σ R = 0     ·     K u = f",
      "Switch to axial tension. Stress becomes nearly uniform away from the clamped edge; bending produces a gradient through the depth.",
      "Why must a static model have enough support constraints?",
      [
        "To prevent rigid-body motion.",
        "To make every stress zero.",
        "To increase the number of elements.",
      ],
      0,
      "Constraints remove translations and rotations that would otherwise require no strain energy. Too many constraints can also make a model artificially stiff.",
    ],
    [
      "assembly",
      "From elements to equations",
      "Small pieces. One connected system.",
      "Explore how local element contributions form a sparse global stiffness matrix.",
      "The weak form balances virtual internal and external work. Each element integrates Bᵀ D B over its domain. Assembly adds contributions at shared degrees of freedom; a node shared by neighboring elements must have one compatible displacement. Most global entries are zero because distant nodes do not share an element.",
      "Kₑ = ∫ Bᵀ D B · t dA     →     K u = f",
      "Separate the elements for inspection, then change mesh density. The matrix diagram comes from the actual assembled system, with two displacement components per node.",
      "Two elements share a node. How are their stiffness contributions combined?",
      [
        "Added at the shared global degrees of freedom.",
        "Averaged into a new isolated node.",
        "Only the stiffer element is retained.",
      ],
      0,
      "Assembly adds contributions. Shared displacements enforce compatibility; assembled nodal forces enforce equilibrium.",
    ],
    [
      "mesh",
      "Mesh & geometry",
      "Resolution is a modeling decision.",
      "Change mesh density and compare a beam with an L-shaped bracket.",
      "A mesh discretizes geometry and the solution field. Refine where gradients are steep, around curved geometry, or near changes in boundary conditions. The bracket contains a sharp re-entrant corner: its idealized stress may keep growing as the mesh is refined. A smooth-looking contour is not evidence of an accurate answer.",
      "h ↓  →  more elements, more degrees of freedom",
      "Compare displacement rather than the highest corner stress when studying a geometric singularity. Local and global quantities converge differently.",
      "A bracket’s sharp-corner peak stress keeps rising under refinement. What should you investigate?",
      [
        "A possible stress singularity.",
        "Whether all materials became nonlinear.",
        "Whether the load disappeared.",
      ],
      0,
      "Sharp corners and idealized point constraints can create singular stresses. Model the actual radius or assess a suitable quantity away from the singularity.",
    ],
    [
      "elements",
      "Element families",
      "Choose an approximation that fits the physics.",
      "Compare constant-strain triangles with bilinear quadrilaterals.",
      "T3 triangles use three nodes and a linear displacement field, giving constant strain in each element. Q4 quadrilaterals use four nodes and bilinear interpolation. This lab integrates T3 exactly and Q4 with a full 2 × 2 Gauss rule. Coarse low-order meshes can be too stiff in bending. Beams, shells, tetrahedra, and hexahedra extend these ideas to other geometric and physical assumptions.",
      "T3: 6 displacement DOFs     ·     Q4: 8 displacement DOFs",
      "Keep material, force, and geometry fixed while changing element family. Compare displacement and computational effort, not just element count.",
      "What is constant inside a linear T3 element in this small-strain model?",
      [
        "Strain and stress.",
        "Every displacement component.",
        "The global reaction force.",
      ],
      0,
      "The spatial derivatives of linear shape functions are constant, so strain is constant. With a uniform elastic material, stress is constant too.",
    ],
    [
      "shape",
      "Shape functions",
      "Watch a node influence an entire element.",
      "Explore the four Q4 basis functions as surfaces and move a probe through natural coordinates.",
      "Shape functions interpolate nodal values throughout an element. A basis function is one at its own node and zero at the others. Their sum is one, allowing a constant field to be reproduced exactly. The vertical axis here is the selected basis value, not a physical displacement.",
      "u(ξ,η) = Σ Nᵢ(ξ,η) uᵢ     ·     Σ Nᵢ = 1",
      "Select each node at the same probe position. The four values always sum to one inside the parent element.",
      "What are the four Q4 shape-function values at the center?",
      ["Each equals 0.25.", "Each equals 1.", "Only one equals 1."],
      0,
      "At ξ = η = 0, every bilinear basis evaluates to ¼. Their sum is one.",
    ],
    [
      "mapping",
      "Mapping & integration",
      "Good geometry makes good mathematics.",
      "Distort a quadrilateral and examine its Jacobian.",
      "Isoparametric elements use the same basis to interpolate coordinates and unknown fields. The Jacobian transforms derivatives and area between natural and physical coordinates. A positive determinant is essential for valid orientation. Small determinants and large variation indicate distortion; a negative determinant means local inversion.",
      "x = Σ Nᵢ xᵢ     ·     dA = det(J) dξ dη",
      "Move the distortion control toward inversion. Watch the minimum determinant and the shape of the physical element. A 2 × 2 rule is standard for Q4; distorted mappings do not make every stiffness integrand a polynomial.",
      "A quadrilateral has a negative Jacobian determinant at a sampled point. What is the best next step?",
      [
        "Repair the element geometry.",
        "Increase the load.",
        "Ignore the sign and take its absolute value.",
      ],
      0,
      "The element is locally inverted. Taking an absolute value hides an invalid mapping rather than repairing it.",
    ],
    [
      "refinement",
      "h versus p refinement",
      "More pieces, or richer pieces?",
      "Approximate a smooth sine field using smaller elements or higher polynomial order.",
      "h refinement reduces element size. p refinement increases interpolation order within each element. For a smooth field, higher-order polynomials can reduce error rapidly. Near discontinuities, corners, or singularities, localized h refinement may be more effective. This experiment measures interpolation error; it is separate from the plane-stress solve.",
      "h = 1 / n     ·     DOFs = n p + 1",
      "Try one quadratic element, then two linear elements. The sample count alone does not describe the approximation space.",
      "Which change is p refinement?",
      [
        "Keeping the mesh and increasing polynomial order.",
        "Dividing every element into smaller elements.",
        "Increasing the applied force.",
      ],
      0,
      "p refers to polynomial degree. h refinement changes element size; hp methods combine both.",
    ],
    [
      "convergence",
      "Convergence & evidence",
      "Trust a trend, not a contour.",
      "Run six actual meshes and track the tip displacement.",
      "A convergence study changes discretization while holding physics fixed. Here each point is a fresh finite-element solve. Compare consecutive values and decide whether the quantity of interest has stabilized. The dashed reference is Euler–Bernoulli beam theory for bending or elementary axial-bar theory for tension; it has different assumptions from a two-dimensional elastic model.",
      "relative change = |u_fine − u_coarse| / |u_fine|",
      "The beam-theory line is a comparison, not the exact answer to this plane-stress boundary-value problem. No beam reference is shown for the bracket.",
      "Successive tip displacements stabilize. Does that prove the material model is correct?",
      [
        "No. Discretization convergence does not validate the physics.",
        "Yes, convergence proves all assumptions.",
        "Yes, if the contour is smooth.",
      ],
      0,
      "Verification asks whether the equations are solved correctly. Validation asks whether those equations represent the physical system.",
    ],
    [
      "solvers",
      "Inside the solver",
      "Follow the residual toward equilibrium.",
      "Inspect a preconditioned conjugate-gradient solve of the assembled system.",
      "After prescribed displacements are eliminated, this elastic stiffness system is symmetric positive definite. A Jacobi-preconditioned conjugate-gradient method solves it without forming an inverse. The residual measures remaining imbalance. A solver tolerance is a numerical stopping criterion, not a guarantee of mesh accuracy.",
      "rₖ = f − K uₖ     ·     stop when ‖rₖ‖ / ‖f‖ < 10⁻⁹",
      "Residual curves need not decrease at every iteration. Inspect the final relative residual and equilibrium reactions.",
      "A tiny solver residual with a very coarse mesh means…",
      [
        "The discrete equations are solved, but the approximation may still be poor.",
        "The solution is exact for the continuous body.",
        "Material properties no longer matter.",
      ],
      0,
      "Algebraic error and discretization error are distinct. Tightening the solver cannot replace a mesh study.",
    ],
    [
      "dynamics",
      "Vibration & modes",
      "Structures have preferred ways to move.",
      "Animate the first three cantilever bending modes and explore their frequency scale.",
      "Free vibration solves a generalized eigenproblem involving stiffness and mass. The animation here uses analytical Euler–Bernoulli cantilever mode shapes, normalized for visibility. Frequencies use the selected modulus, beam dimensions, and a density of 2700 kg/m³. These are analytical beam predictions, separate from the static 2D solver.",
      "K φ = ω² M φ     ·     fₙ = βₙ² √(EI / ρA) / (2π L²)",
      "Higher modes have more internal nodes. The animation is slowed and normalized; its playback speed is not the physical frequency.",
      "If stiffness increases while mass stays fixed, natural frequencies generally…",
      ["Increase.", "Decrease.", "Remain identical."],
      0,
      "For a fixed mode, frequency scales with the square root of stiffness divided by mass.",
    ],
    [
      "heat",
      "Beyond structures: heat",
      "The same framework, a different field.",
      "Explore steady conduction through a plate with prescribed edge temperatures.",
      "Finite elements also approximate temperature, electric potential, and other fields. This homogeneous plate has prescribed left and right temperatures and insulated top and bottom boundaries. Its exact steady temperature profile is linear. The visual surface thickness is illustrative; heat flows from hot to cold, opposite the temperature gradient.",
      "qₓ = −k dT/dx     ·     T(x) = T_hot + (T_cold − T_hot)x/L",
      "Swap the edge temperatures. The heat-flow direction reverses. A nonlinear temperature field would require different geometry, properties, sources, or boundary conditions.",
      "Doubling conductivity with fixed edge temperatures changes…",
      [
        "Heat flux, but not this steady linear temperature profile.",
        "Only the cold-edge temperature.",
        "The temperature into a quadratic curve.",
      ],
      0,
      "The prescribed temperatures fix the profile in this uniform, source-free problem. Conductivity scales the resulting heat flux.",
    ],
    [
      "verification",
      "Verification & judgment",
      "Know what your model can claim.",
      "Check force balance and separate numerical evidence from physical assumptions.",
      "This model assumes small strains, linear isotropic elasticity, and plane stress. It does not predict yielding, fracture, contact, or large-deformation behavior. An exaggerated deformation can look nonlinear even when the equations are linear. A complete engineering workflow checks units, reactions, mesh sensitivity, material data, and agreement with relevant measurements.",
      "verification ≠ validation     ·     equilibrium is necessary, not sufficient",
      "A bracket corner peak is especially sensitive to idealization. Do not compare it directly with material strength without understanding singularities and the actual geometry.",
      "What would establish physical validation?",
      [
        "Comparison with relevant experimental measurements.",
        "A smaller residual alone.",
        "A more dramatic deformation scale.",
      ],
      0,
      "Experiments test whether the model captures reality under the conditions of interest. Mesh and solver checks establish numerical confidence.",
    ],
    [
      "abaqus",
      "Take the model further",
      "Turn an experiment into a reproducible model.",
      "Export the current mesh, material, constraints, and loads as an Abaqus input deck.",
      "The export uses CPS3 or CPS4 plane-stress elements, consistent nodal loads, and the same N–mm–MPa unit system as this lab. It includes a static step and a homogeneous solid section. It is a starting point for comparison in Abaqus, not a substitute for reviewing assumptions, element formulations, and output definitions.",
      "CPS3 ↔ T3     ·     CPS4 ↔ Q4",
      "Compare nodal displacements and total reactions first. Stress recovery and extrapolation conventions may differ between solvers.",
      "What must remain consistent in an exported model?",
      [
        "Geometry, units, materials, loads, and constraints.",
        "Only its visual color scheme.",
        "Only the element numbering.",
      ],
      0,
      "A meaningful cross-solver comparison requires the same boundary-value problem and compatible element assumptions.",
    ],
  ];
  const hpc = [
    [
      "scaling",
      "Parallel scaling",
      "More processors. How much faster?",
      "Watch work spread across a cluster and discover where speedup stops.",
      "A parallel program has work that can be distributed and work that must remain serial. Amdahl’s law predicts strong-scaling speedup for a fixed problem size. This lab adds an explicit communication term that grows with log₂(P). That overhead is a teaching model, not a measurement of a particular supercomputer.",
      "T(P) = T₁[(1 − f) + f/P + α log₂(P)]",
      "Set communication to zero, then increase the serial fraction. Even unlimited processors cannot remove serial work.",
      "If 10% of a fixed workload is serial, what is the ideal speedup limit?",
      ["10×.", "100×.", "Unlimited."],
      0,
      "As P approaches infinity, the parallel term vanishes and speedup approaches 1 / 0.1 = 10.",
    ],
    [
      "rightsizing",
      "Right-size the resources",
      "The smallest suitable machine wins.",
      "Match memory and parallelism requirements to a resource.",
      "A job should fit in memory and use the parallel resources it requests. More cores can increase allocation cost without meaningfully reducing runtime. Compare a laptop, a CPU node, a GPU node, and a distributed cluster using transparent teaching capacities. Specialized accelerators help only when software and workload can use them.",
      "fit first → parallel benefit → allocation cost",
      "Select a workload, then a resource. The recommendation considers memory capacity, accelerator suitability, and distributed execution requirements.",
      "A serial job needs 8 GB RAM. Which is the most reasonable starting point?",
      [
        "A workstation with enough memory.",
        "A large distributed allocation.",
        "A GPU regardless of software support.",
      ],
      0,
      "A serial workload cannot use extra CPU ranks. Start with the smallest resource that satisfies memory and software requirements.",
    ],
    [
      "workflow",
      "The life of a job",
      "From request to result.",
      "Submit a simulated batch job and follow its queue, run, and completion stages.",
      "A scheduler matches resource requests to available capacity. A job waits until resources are available, runs within its allocation, and writes results. This miniature scheduler uses a deterministic teaching queue. The generated Slurm script reflects requested nodes and walltime; running the demonstration does not submit anything to an actual cluster.",
      "submit → pending → allocated → running → complete",
      "Try a very short walltime. A scheduler can stop a healthy computation simply because its requested time limit expires.",
      "A job is pending. What does that necessarily tell you?",
      [
        "It has not started running yet.",
        "Its source code has a bug.",
        "The computation has finished.",
      ],
      0,
      "Pending means waiting. Resource availability, priority, dependencies, and policy are among the possible reasons.",
    ],
    [
      "architecture",
      "CPU versus GPU",
      "Different engines for different work.",
      "Compare a few flexible lanes with many throughput-oriented lanes.",
      "CPUs suit latency-sensitive work and complex control flow. GPUs excel when large batches perform similar operations with sufficient parallelism and data reuse. The lane counts in this scene are illustrative. A GPU is not automatically faster: transfers, launch overhead, branch divergence, and small batches can erase the advantage.",
      "T_accelerated = T_transfer + T_launch + T_parallel",
      "Increase the batch size and compare predicted CPU and GPU time. A crossover can appear because fixed overhead matters most for small jobs.",
      "Which workload is most naturally suited to a GPU?",
      [
        "A large batch of independent, similar operations.",
        "A tiny serial task with unpredictable branches.",
        "Any task, regardless of implementation.",
      ],
      0,
      "Many similar independent operations expose the parallelism a GPU needs. Efficient data movement and an appropriate implementation still matter.",
    ],
    [
      "memory",
      "The memory hierarchy",
      "Fast arithmetic needs nearby data.",
      "Explore the tradeoff between memory capacity and access latency.",
      "Registers and caches are small and fast; main memory is larger and slower; storage is larger still. Locality reuses nearby data before it is evicted. The displayed latencies are teaching assumptions, not hardware benchmarks. More arithmetic units do not help much if they spend their time waiting for data.",
      "effective latency = hit rate × cache latency + miss rate × memory latency",
      "Raise the cache-hit rate. A small change near a high hit rate can still affect average access cost. Real processors overlap accesses, so this serial-access model does not predict total application runtime.",
      "Which change most directly improves temporal locality?",
      [
        "Reusing data before it leaves cache.",
        "Reading every item once in a random order.",
        "Increasing network distance.",
      ],
      0,
      "Temporal locality is reuse over a short interval. Spatial locality uses nearby addresses, often within the same cache line.",
    ],
    [
      "roofline",
      "The roofline model",
      "Find the bottleneck before optimizing.",
      "Balance arithmetic intensity, memory bandwidth, and compute throughput.",
      "The roofline model bounds attainable throughput by the smaller of peak compute and bandwidth times arithmetic intensity. Intensity is floating-point operations per byte transferred from the modeled memory level. The knee separates bandwidth-bound and compute-bound regions. The plot is a simplified upper bound; real performance can be lower.",
      "performance ≤ min(peak FLOP/s, bandwidth × FLOP/byte)",
      "Increase intensity while keeping the machine fixed. Once you reach the flat roof, additional reuse alone cannot raise this bound.",
      "A memory-bound kernel is most directly helped by…",
      [
        "Reducing transferred bytes or increasing bandwidth.",
        "Raising peak arithmetic throughput alone.",
        "Adding unnecessary memory traffic.",
      ],
      0,
      "On the sloped part of the roofline, the bound is bandwidth times intensity. Compute capability is not yet the limiting factor.",
    ],
    [
      "network",
      "Communication & topology",
      "Moving data is part of computing.",
      "Explore message latency, transfer time, and collective communication.",
      "Distributed workers exchange data through an interconnect. A message has a startup cost plus a size-dependent transfer cost. A simple tree collective takes about log₂(P) stages. The model here assumes a full message at each stage and no overlap; production collective algorithms can use different traffic patterns and costs.",
      "T_message = latency + bytes / bandwidth",
      "Try tiny and large messages. Latency dominates small transfers; bandwidth dominates large ones. Increasing worker count adds stages in this tree model.",
      "What dominates the time of a very small message?",
      [
        "Startup latency.",
        "Only message size.",
        "The number of floating-point operations.",
      ],
      0,
      "For very small messages, bytes / bandwidth is small, leaving the fixed startup latency as the dominant term.",
    ],
    [
      "scheduling",
      "Queues & utilization",
      "Keep the machine usefully busy.",
      "Compare first-in-first-out scheduling with safe backfilling.",
      "A large waiting job can leave idle slots while a smaller job could run. Backfilling allows a later job to use those slots if it will finish before the reservation for the earlier job. This fixed example contrasts the two policies without introducing priorities or fairness weights.",
      "utilization = busy processor-time / available processor-time",
      "The chart uses four slots. A running job occupies two until t = 4; job A needs four for six time units; job B needs two for three. Backfilling B preserves A’s start time.",
      "When is backfilling safe with respect to a reserved job?",
      [
        "When the smaller job does not delay the reservation.",
        "Whenever a later job exists.",
        "Only after all processors are idle.",
      ],
      0,
      "Conservative backfilling protects reservations. More advanced scheduling adds priority, fairness, topology, and other resource constraints.",
    ],
    [
      "energy",
      "Time, cost & energy",
      "Faster is only one objective.",
      "Compare runtime, allocated processor-time, and an illustrative energy estimate.",
      "Strong scaling can shorten runtime while increasing processor-seconds and energy. The energy model combines a fixed platform power with a per-allocated-worker power. It intentionally omits cooling, frequency scaling, and detailed idle behavior. Use it to reason about tradeoffs, not to estimate a real electricity bill.",
      "energy = (base power + P × worker power) × runtime",
      "Find the lowest runtime, then compare its energy with a smaller allocation. The two optima need not coincide.",
      "Does the fastest configuration always consume the least energy?",
      [
        "No; power and runtime both matter.",
        "Yes, by definition.",
        "Only processor count matters.",
      ],
      0,
      "Energy is the integral of power over time. A larger allocation may save too little time to compensate for higher power.",
    ],
  ];
  const convert = (rows) =>
    rows.map((r, i) => ({
      id: r[0],
      nav: r[1],
      title: r[2],
      subtitle: r[3],
      body: r[4],
      equation: r[5],
      takeaway: r[6],
      question: r[7],
      answers: r[8],
      correct: r[9],
      feedback: r[10],
      index: i,
    }));
  window.LabCurriculum = { fea: convert(fe), hpc: convert(hpc) };
})();
